구현 : 바코드 페이지& 쓰샘 기기 이용안내 페이지
kookmin-sw/capstone-2021-3 pull request #125
Opened 2021-05-12 13:38 UTC by TongSeola

2021-05-12 16:26 UTC, Aqudi requested changes
수정할 내용들 남겼습니다!

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/map_page.dart
> +  var barcodeButton = DrawerItem(
변하지 않는 값들은 final로 선언해주세요.

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/barcode_page.dart
> +    var screenWidth = screenSize.width;
변하지 않는 값은 final로 선언해주세요.

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/information_page.dart
> +
사용한 controller는 dispose 호출해주세요.  

```dart
@override
void dispose() {
    pagecontroller.dispose();
    super.dispose()
}

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/information_page.dart
> +    this.pagecontroller = PageController(
this. 은 다른 곳에서 this.selectedIndex로 안 썼으니까 지우시는게 좋을 것 같아요.

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/information_page.dart
> +    var screenWidth = screenSize.width;
변하지 않는 값들은 final로 선언해주세요.

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/information_page.dart
> +    var screenHeight = screenSize.height;
변하지 않는 값들은 final로 선언해주세요.

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/information_page.dart
> +    var screenHeight = screenSize.height;
변하지 않는 값들은 final로 선언해주세요.

2021-05-12 16:26 UTC, Aqudi commented on app/inobus/lib/pages/information_page.dart
> +                    onDotClicked: (index) {}),
일부러 구현 안하신건가요?
그렇다면 null을 넣어서 클릭이 안되게 하는 게 좋을 것 같네요.

2021-05-14 05:25 UTC, Aqudi reviewed
페이지 넘기는 코드는 어딨는건가요?

2021-05-14 05:54 UTC, TongSeola commented
> 페이지 넘기는 코드는 어딨는건가요?

이용안내 페이지 말하는 건가요? 그런거라면 InformationPage에 PageView로 만들어서 가로로 넘어가게 만들었습니다.

2021-05-16 05:55 UTC, Aqudi approved these changes
LGMT!

2021-05-16 08:14 UTC, merged