쓰샘 기기용 REST API 구현
kookmin-sw/capstone-2021-3 pull request #144
Opened 2021-05-19 20:42 UTC by ParkJeongseop

+ 쓰샘 기기에서 컵투입시 단체 포인트 등록 후 레코드 키 반환
+ 쓰샘 기기에서 사용자 바코드 등록 시 해당 레코드키와 사용자 바코드 정보를 이용해 사용자 포인트 등록 및 레코드 갱신
+ Firebase 사용자 데이터를 조회하여 유효성 검사 및 사용자 디스플레이네임(닉네임)을 서비스의 닉네임으로 사용
+ 사용자 식별자 기반 현재달의 추첨권 보유량 반환 API 구현
+ 바코드가 가변 값에서 사용자 식별자를 이용한 고정 값으로 변경
+ 따라서 가변 바코드 생성 API 삭제
+ 회원 관리 기능을 자체 DB에서 모바일앱에서 빠른 구현을 위해 Firebase사용으로 관련 API 제거

2021-05-20 05:06 UTC, Aqudi requested changes
전체적으로 model 클래스에 정의된 내용들을 활용해야할 필요성이 보입니다.

2021-05-20 05:06 UTC, Aqudi commented on backend/models/user.py
> +    _id: Optional[PyObjectId] = Field(alias="_id")
다른 모델에는 id로 되어 있는데 _id로 바꾼 이유가 있나요?
alias로 _id를 지정했을 경우 `User.parse_obj(dict)` 나 `User.parse_raw(string)` 실행 시에는 _id를 id로 가져옵니다.

반대로 직렬화 오브젝트 -> dict, 오브젝트 -> json string 일 때는 
`User.dict(by_alias=False)`, `User.json(by_alias=True)` 사용하면 됩니다.

2021-05-20 05:06 UTC, Aqudi commented on backend/models/user.py
> +                "user_name": "우주최강개발자 박정섭",
id는 반환하지 않나요?

2021-05-20 05:06 UTC, Aqudi commented on backend/routes/rewards.py
> +    device = db.devices.find_one({"_id": ObjectId(device_id)})
model 클래스에 넣은 다음에 사용을 하면 좋을 것 같습니다.
`Device.parse_obj(device)`를 사용하면 될 것 같네요.

2021-05-20 05:06 UTC, Aqudi commented on backend/routes/rewards.py
> +    organization = db.organizations.find_one({"name": org_name})
여기도 마찬가지로 model 클래스를 활용하는 것이 데이터가 좀 일관성 있게 유지될 것 같네요.

2021-05-20 15:46 UTC, ParkJeongseop commented on backend/models/data.py
>      user: Optional[PyObjectId] = Field(description="포인트를 쌓은 유저 id")
user의 타입을 str로 변경하였습니다

2021-05-20 15:53 UTC, ParkJeongseop commented on backend/models/user.py
> +                "user_name": "우주최강개발자 박정섭",
UserTicket모델은 몽고디비에 저장하지않고 요청시에 서버에서 생성하는 데이터모델이라 해당 객체의 id는 없어서 반환을 안합니다. API문서 예제때문에 여기에 모델로 생성하긴했는데 이렇게 하는게 아닌가요..?

2021-05-22 05:52 UTC, Aqudi reviewed
리뷰남겼습니다!

2021-05-22 05:52 UTC, Aqudi commented on backend/models/data.py
> +    organization: PyObjectId = Field(description="데이터의 디바이스 id")
organization 필드 설명 변경이 필요하네요

2021-05-22 05:52 UTC, Aqudi commented on backend/models/device.py
> +    install_date: str
필드타입 확인해주세요

2021-05-22 05:52 UTC, Aqudi commented on backend/utils/firebasedb.py
> +    return "success", m_user
line ending 없음

2021-05-22 06:50 UTC, Aqudi reviewed
리뷰 남겼습니다.

2021-05-22 06:50 UTC, Aqudi commented on backend/routes/organizations.py
>      ]
organization_name -> organization 이었던 것 같은데 다시 확인해주세요.

2021-05-22 06:50 UTC, Aqudi commented on backend/routes/rewards.py
> +        raise HTTPException(status_code=404, detail="Access denied")
status_code 400이나 409 여야 할 것 같습니다.

2021-05-22 06:50 UTC, Aqudi commented on backend/routes/rewards.py
> +        raise HTTPException(status_code=404, detail="Access denied")
status_code가 400이어야 할 것 같습니다.

2021-05-22 06:50 UTC, Aqudi commented on backend/routes/rewards.py
> +        print("Access denied: device_id is not matched!")
status_code가 400이어야 할 것 같습니다.

2021-05-22 06:50 UTC, Aqudi commented on backend/routes/rewards.py
> +    return "ss"
지워주세요.

2021-05-22 08:58 UTC, Aqudi approved these changes
LGTM

2021-05-22 08:58 UTC, merged