리팩터: database.py를 utils에 포함
kookmin-sw/capstone-2021-3 pull request #60
Opened 2021-03-24 03:55 UTC by ParkJeongseop

+ /database.py에서 /utils/database.py로 변경
+ 폴더 및 파일 구조 문서 수정

2021-03-24 05:31 UTC, Aqudi requested changes
master Pull 을 한 번 받으신 후에 rebase 하시고 올려주시면 좋을 것 같습니다.

2021-03-24 22:14 UTC, ParkJeongseop commented
> master Pull 을 한 번 받으신 후에 rebase 하시고 올려주시면 좋을 것 같습니다.

마스터에서 재배치하였습니다.

2021-03-25 10:02 UTC, Aqudi commented
> > master Pull 을 한 번 받으신 후에 rebase 하시고 올려주시면 좋을 것 같습니다.
> 
> 마스터에서 재배치하였습니다.

문서 수정한 내용들이 수정전으로 돌아갔습니다...

2021-03-25 10:03 UTC, Aqudi requested changes

2021-03-25 10:03 UTC, Aqudi commented on backend/README.md
> +  - [Docker 저장소 주소](https://hub.docker.com/repository/docker/taejung/ino_api)
여기도 그렇고 README.md 쪽은 다 이전으로 돌아갔네요

2021-03-31 04:45 UTC, Aqudi commented
새로 브랜치를 파서 하는 것이 좋을 것 같습니다!

2021-03-31 04:45 UTC, closed without merging